/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpr.poo.pizzaria;

/**
 *
 * @author everaldo
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoesTipoMassa = new javax.swing.ButtonGroup();
        grupoBotoesTamanhoPizza = new javax.swing.ButtonGroup();
        tipoMassaPainel = new javax.swing.JPanel();
        massaNormalRadioButton = new javax.swing.JRadioButton();
        massaSemGlutenRadioButton = new javax.swing.JRadioButton();
        coberturasPainel = new javax.swing.JPanel();
        atumCheckBox = new javax.swing.JCheckBox();
        calabresaCheckBox = new javax.swing.JCheckBox();
        frangoCheckBox = new javax.swing.JCheckBox();
        manjericaoCheckbox = new javax.swing.JCheckBox();
        mussarelaCheckBox = new javax.swing.JCheckBox();
        tomatesCheckBox = new javax.swing.JCheckBox();
        resumoPedidoPainel = new javax.swing.JPanel();
        tamanhoPainel = new javax.swing.JPanel();
        tamanhoPequenoRadioButton = new javax.swing.JRadioButton();
        tamanhoMedioRadioButton = new javax.swing.JRadioButton();
        tamanhoGrandeRadioButton = new javax.swing.JRadioButton();
        tamanhoGiganteRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzaria");

        tipoMassaPainel.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha o Tipo da Massa"));

        grupoBotoesTipoMassa.add(massaNormalRadioButton);
        massaNormalRadioButton.setText("Massa Normal");

        grupoBotoesTipoMassa.add(massaSemGlutenRadioButton);
        massaSemGlutenRadioButton.setText("Massa sem glúten");

        javax.swing.GroupLayout tipoMassaPainelLayout = new javax.swing.GroupLayout(tipoMassaPainel);
        tipoMassaPainel.setLayout(tipoMassaPainelLayout);
        tipoMassaPainelLayout.setHorizontalGroup(
            tipoMassaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoMassaPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(massaNormalRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(massaSemGlutenRadioButton)
                .addContainerGap())
        );
        tipoMassaPainelLayout.setVerticalGroup(
            tipoMassaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoMassaPainelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tipoMassaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(massaNormalRadioButton)
                    .addComponent(massaSemGlutenRadioButton))
                .addContainerGap())
        );

        coberturasPainel.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha as Coberturas"));

        atumCheckBox.setText("Atum");
        atumCheckBox.setActionCommand("atum");

        calabresaCheckBox.setText("Calabresa");
        calabresaCheckBox.setActionCommand("calabresa");

        frangoCheckBox.setText("Frango");
        frangoCheckBox.setActionCommand("frango");

        manjericaoCheckbox.setText("Manjericão");
        manjericaoCheckbox.setActionCommand("manjericao");

        mussarelaCheckBox.setText("Mussarela");
        mussarelaCheckBox.setActionCommand("mussarela");

        tomatesCheckBox.setText("Tomates");
        tomatesCheckBox.setActionCommand("tomates");

        javax.swing.GroupLayout coberturasPainelLayout = new javax.swing.GroupLayout(coberturasPainel);
        coberturasPainel.setLayout(coberturasPainelLayout);
        coberturasPainelLayout.setHorizontalGroup(
            coberturasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coberturasPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coberturasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coberturasPainelLayout.createSequentialGroup()
                        .addComponent(atumCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(frangoCheckBox)
                        .addGap(37, 37, 37))
                    .addGroup(coberturasPainelLayout.createSequentialGroup()
                        .addComponent(calabresaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manjericaoCheckbox)
                        .addGap(13, 13, 13)))
                .addGroup(coberturasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tomatesCheckBox)
                    .addComponent(mussarelaCheckBox)))
        );
        coberturasPainelLayout.setVerticalGroup(
            coberturasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coberturasPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coberturasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atumCheckBox)
                    .addComponent(frangoCheckBox)
                    .addComponent(mussarelaCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coberturasPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calabresaCheckBox)
                    .addComponent(manjericaoCheckbox)
                    .addComponent(tomatesCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        resumoPedidoPainel.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo do Pedido"));

        javax.swing.GroupLayout resumoPedidoPainelLayout = new javax.swing.GroupLayout(resumoPedidoPainel);
        resumoPedidoPainel.setLayout(resumoPedidoPainelLayout);
        resumoPedidoPainelLayout.setHorizontalGroup(
            resumoPedidoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        resumoPedidoPainelLayout.setVerticalGroup(
            resumoPedidoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );

        tamanhoPainel.setBorder(javax.swing.BorderFactory.createTitledBorder("Escolha o Tamanho"));

        grupoBotoesTamanhoPizza.add(tamanhoPequenoRadioButton);
        tamanhoPequenoRadioButton.setText("Pequena");

        grupoBotoesTamanhoPizza.add(tamanhoMedioRadioButton);
        tamanhoMedioRadioButton.setText("Média");

        grupoBotoesTamanhoPizza.add(tamanhoGrandeRadioButton);
        tamanhoGrandeRadioButton.setText("Grande");

        grupoBotoesTamanhoPizza.add(tamanhoGiganteRadioButton);
        tamanhoGiganteRadioButton.setText("Gigante");

        javax.swing.GroupLayout tamanhoPainelLayout = new javax.swing.GroupLayout(tamanhoPainel);
        tamanhoPainel.setLayout(tamanhoPainelLayout);
        tamanhoPainelLayout.setHorizontalGroup(
            tamanhoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tamanhoPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tamanhoPequenoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(tamanhoMedioRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tamanhoGrandeRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tamanhoGiganteRadioButton)
                .addContainerGap())
        );
        tamanhoPainelLayout.setVerticalGroup(
            tamanhoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tamanhoPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tamanhoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamanhoPequenoRadioButton)
                    .addComponent(tamanhoGrandeRadioButton)
                    .addComponent(tamanhoMedioRadioButton)
                    .addComponent(tamanhoGiganteRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tamanhoPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tipoMassaPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(coberturasPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(resumoPedidoPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tamanhoPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoMassaPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coberturasPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resumoPedidoPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox atumCheckBox;
    private javax.swing.JCheckBox calabresaCheckBox;
    private javax.swing.JPanel coberturasPainel;
    private javax.swing.JCheckBox frangoCheckBox;
    private javax.swing.ButtonGroup grupoBotoesTamanhoPizza;
    private javax.swing.ButtonGroup grupoBotoesTipoMassa;
    private javax.swing.JCheckBox manjericaoCheckbox;
    private javax.swing.JRadioButton massaNormalRadioButton;
    private javax.swing.JRadioButton massaSemGlutenRadioButton;
    private javax.swing.JCheckBox mussarelaCheckBox;
    private javax.swing.JPanel resumoPedidoPainel;
    private javax.swing.JRadioButton tamanhoGiganteRadioButton;
    private javax.swing.JRadioButton tamanhoGrandeRadioButton;
    private javax.swing.JRadioButton tamanhoMedioRadioButton;
    private javax.swing.JPanel tamanhoPainel;
    private javax.swing.JRadioButton tamanhoPequenoRadioButton;
    private javax.swing.JPanel tipoMassaPainel;
    private javax.swing.JCheckBox tomatesCheckBox;
    // End of variables declaration//GEN-END:variables
}
